// default package
// Generated Feb 28, 2016 12:05:34 AM by Hibernate Tools 4.3.1.Final

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private int id;
	private String name;
	private int age;
	private String address;
	private Float salary;

	public Company() {
	}

	public Company(int id, String name, int age) {
		this.id = id;
		this.name = name;
		this.age = age;
	}

	public Company(int id, String name, int age, String address, Float salary) {
		this.id = id;
		this.name = name;
		this.age = age;
		this.address = address;
		this.salary = salary;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Float getSalary() {
		return this.salary;
	}

	public void setSalary(Float salary) {
		this.salary = salary;
	}

}
