// default package
// Generated Feb 28, 2016 12:05:34 AM by Hibernate Tools 4.3.1.Final

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private int id;
	private String firstName;
	private String lastName;

	public Person() {
	}

	public Person(int id, String firstName, String lastName) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

}
